name: 'Zephir Parser PHP extension build action'
description: 'Build Zephir Parser for macOS according to various PHP versions.'

runs:
  using: 'composite'
  steps:
    - name: Install RE2C Lexer Generator
      shell: bash
      run: brew install re2c lcov
      env:
        HOMEBREW_NO_INSTALL_CLEANUP: "1"

    - name: Build Zephir Parser for macOS
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        echo "::group::Run phpize"
        phpize
        echo "::endgroup::"

        echo "::group::Run configure"
        ./configure \
            --enable-zephir-parser \
            --enable-zephir-parser-debug \
            ${{ env.CONFIGURE_COVERAGE }}
        echo "::endgroup::"

        echo "::group::Compile"
        make -j$(getconf _NPROCESSORS_ONLN)
        echo "::endgroup::"

    - name: Preparing to collect coverage data
      if: matrix.ccov == 'ON'
      shell: bash
      run: make coverage-initial

    - name: Enable Zephir Parser
      shell: bash
      run: |
        php --ini
        cp ./modules/zephir_parser.so "$(php -r 'echo ini_get("extension_dir");')/zephir_parser.so"
        if [ "${{ matrix.ts }}" = "ts" ]; then
            echo "extension=zephir_parser.so" > /opt/homebrew/etc/php/${{ matrix.php }}-zts/conf.d/ext-zephir_parser.ini
        else
            echo "extension=zephir_parser.so" > /opt/homebrew/etc/php/${{ matrix.php }}/conf.d/ext-zephir_parser.ini
        fi
